baseURL = "https://akutschi.gitlab.io/dokugo/"
languageCode = "en-us"
title = "DoKugo"
theme = "dokugo"



[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  homeText = "No eye candy!"
  dateFormat = "2006-01-02"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    pre = "book"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
