baseURL = "https://akutschi.github.io/dokugo/"
languageCode = "en-us"
title = "DoKugo"
theme = "dokugo"
enableEmoji = true  


[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  homeText = "Simplicity!"
  dateFormat = "2006-01-02"

[params.footer]
  footerText = "This is a very simple and clean theme for documentation purposes. Main goal is a layout that does not distract the reader and can be navigated easily."  
  github = "https://github.com/akutschi/dokugo"
  gitlab = ""
  # This line enables (true) or disables (false) the "Powered by Hugo. Theme DoKugo." line.
  poweredByLine = true 

[params.footer.links]
  [[params.footer.links.content]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[params.footer.links.content]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[params.footer.links.content]]
    name = "Documentation"
    url = "/documentation/"
    weight = 3
  [[params.footer.links.content]]
    name = "Categories"
    url = "/categories/"
    weight = 4
  [[params.footer.links.content]]
    name = "Tags"
    url = "/tags/"
    weight = 5
  [[params.footer.links.quick]]
    name = "About"
    url = "/about/"
    weight = 1
  [[params.footer.links.quick]]
    name = "Contact"
    url = "/contact/"
    weight = 2
  [[params.footer.links.quick]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 3

[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = true
    style = "solarized-dark"
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
   [[menu.main]]
    name = "Documentation"
    url = "/documentation/"
    weight = 3
  
